
name: Handle pull requests with new tests

on:

  push:
    branches: [ "testing-with-jest"]
  pull_request:
    branches: [ "testing-with-jest"]


  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
